/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dice;
import java.awt.*;

/**
 *
 * @author student
 */
public class dice2 extends javax.swing.JApplet {

    /**
     * Initializes the applet dice2
     */
    int r;
    int size;
    int x;
    int y;
    int colour;
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jButton1.setText("Roll");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 319, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void die(Graphics gr, int value, int x, int y, int size, int colour)
    {
        gr.setColor (Color.RED);
        gr.fillRect (x, y, size, size);
        gr.setColor (Color.WHITE);
        switch (r)
        {
            case 1:
                gr.fillOval ((4 * size/10) + x, (4 * size/10) + y, size/5, size/5);
                break;
            case 2:
                gr.fillOval ((1 * size/10) + x, (1 * size/10) + y, size/5, size/5);
                gr.fillOval ((7 * size/10) + x, (7 * size/10) + y, size/5, size/5);
                break;
            case 3:
                gr.fillOval ((1 * size/10) + x, (1 * size/10) + y, size/5, size/5);
                gr.fillOval ((4 * size/10) + x, (4 * size/10) + y, size/5, size/5);
                gr.fillOval ((7 * size/10) + x, (7 * size/10) + y, size/5, size/5);
                break;
            case 4:
                gr.fillOval ((1 * size/10) + x, (1 * size/10) + y, size/5, size/5);
                gr.fillOval ((1 * size/10) + x, (7 * size/10) + y, size/5, size/5);
                gr.fillOval ((7 * size/10) + x, (1 * size/10) + y, size/5, size/5);
                gr.fillOval ((7 * size/10) + x, (7 * size/10) + y, size/5, size/5);
                break;
            case 5:
                gr.fillOval ((1 * size/10) + x, (1 * size/10) + y, size/5, size/5);
                gr.fillOval ((1 * size/10) + x, (7 * size/10) + y, size/5, size/5);
                gr.fillOval ((4 * size/10) + x, (4 * size/10) + y, size/5, size/5);
                gr.fillOval ((7 * size/10) + x, (1 * size/10) + y, size/5, size/5);
                gr.fillOval ((7 * size/10) + x, (7 * size/10) + y, size/5, size/5);
                break;
            case 6:
                gr.fillOval ((1 * size/10) + x, (1 * size/10) + y, size/5, size/5);
                gr.fillOval ((1 * size/10) + x, (4 * size/10) + y, size/5, size/5);
                gr.fillOval ((1 * size/10) + x, (7 * size/10) + y, size/5, size/5);
                gr.fillOval ((7 * size/10) + x, (1 * size/10) + y, size/5, size/5);
                gr.fillOval ((7 * size/10) + x, (4 * size/10) + y, size/5, size/5);
                gr.fillOval ((7 * size/10) + x, (7 * size/10) + y, size/5, size/5);
                break;
        }

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        r = (int) ((Math.random () * 6) + 1);
        Graphics g = jPanel1.getGraphics();
        size = 200;
        x = 100;
        y = 100;
        colour = 1;
        die(g, r, x, y, size, colour);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
